### ISSUE TITLE
Swagger文档无法查看

### ISSUE THREAD

**Issue by icuxika** [Jiiiiiin/jiiiiiin-security#14]
一直提示：Unable to infer base url. This is common when using dynamic servlet registration or when the API is behind an API Gateway. The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/. Please enter the location manually:

**Comment by Jiiiiiin** [comment]
@icuxika 下个版本将会更新由网关聚合出来可以分组（区分service）的swagger api管理版本，估计今天或者明天吧，使用的是：
# https://github.com/SpringForAll/spring-boot-starter-swagger
类似：
![](http://ww4.sinaimg.cn/large/006tNc79gy1g3h2rol65mj31cy0u0wuh.jpg)

目前正在测试中~~

**Comment by Jiiiiiin** [comment]
@icuxika 已经修复，可以查看https://github.com/Jiiiiiin/jiiiiiin-security/commit/8bc0f271eee99215dff3956e78d0ecc87ae1b320
