### ISSUE TITLE
每次登陆都重置了验证码

### ISSUE THREAD

**Issue by SLin0218** [Jiiiiiin/jiiiiiin-security#15]
```
2019-06-17 23:37:36.681  INFO 6330 --- [nio-9090-exec-5] c.j.s.c.v.c.i.ImageValidateCodeGenerator : 图形验证码 9V 有效期 60
2019-06-17 23:37:36.686  INFO 6330 --- [nio-9090-exec-6] c.j.s.c.v.code.ValidateCodeFilter        : 校验请求(/mng/authentication/form)中的验证码,验证码类型IMAGE
2019-06-17 23:37:36.686  INFO 6330 --- [nio-9090-exec-6] .s.c.v.c.i.AbstractValidateCodeProcessor : 验证码 imageCode::code cn.jiiiiiin.security.core.validate.code.entity.ValidateCode@307937d1 validateCode pm
2019-06-17 23:37:36.686 ERROR 6330 --- [nio-9090-exec-6] c.j.s.c.v.code.ValidateCodeFilter        : 验证码校验失败
```

__`.env.development`__
```
# 后台的url
# VUE_APP_SEVER_URL=http://192.168.3.43:9000
VUE_APP_SEVER_URL=http://localhost:9000

# 后端的swagger api页面地址
VUE_APP_SWAGGER_API_URL=http://localhost:9000/mng/swagger-ui.html
```

__`dev-server.config.js`__
```
module.exports = {
  proxy: {
    '/mng': {
      target: 'http://localhost:9090',
      pathRewrite: {
        '^/mng': '/mng'
      },
      changeOrigin: true
    }
  },
  open: false,
  quiet: false
}
```
点击登陆会先刷新验证码, 然后验证码不对了, 对 Vue 不是很熟。

**Comment by Jiiiiiin** [comment]
@SLin0218 你用的是master分支？你可以尝试跟一下ImageValidateCodeGenerator逻辑，目前主要维护的springcloud分支，验证码是在网关的对应filter拦截，目前该分支已经没有9090的后端服务，如果是master分支，这个配置应该应该没问题，dev-server哪里就是配置webpack dev-server的代理映射，你可以检查一下对应的9090后端服务是否配置了上下文/mng，那个分支的验证码是存储在session中。
应该问题不大，需要注意的是你浏览器打开的url应该是前端的对应9000，可以监控一下调试面板，是否存在跨域问题，一般这种情况都是因为跨域导致。

**Comment by SLin0218** [comment]
对的, 是 `master` 分支, `dev-serve` 中配置后解决了跨域问题.
验证码保存在 `session` 中. 

每次验证登录的时候, 会先触发刷新验证码, 在 `Google Console - network` 中, 在登录请求之前会有一个 `image` 的请求.
在后台断点, `Sesssion save` 方法, 会先进去这个, 然后再进 `get` 方法, 之前看到的验证码已经被覆盖, 后台对比然后验证码不一致.

**Comment by Jiiiiiin** [comment]
@SLin0218 请查考 #8 然后对照README中文档检查一下

**Comment by SLin0218** [comment]
@Jiiiiiin 
![image](https://user-images.githubusercontent.com/23139501/59684364-6e577900-920c-11e9-98df-edad5166f387.png)
![image](https://user-images.githubusercontent.com/23139501/59684394-7f07ef00-920c-11e9-8310-0f3e068c7178.png)

在点击登陆的时候, 验证码会提前刷新. 加了代理后目前没有提示跨域问题.
验证码是存储在 `session` 中, 没有存储到 `Redis`

**Comment by Jiiiiiin** [comment]
登录不进去吗？还是啥

**Comment by SLin0218** [comment]
@Jiiiiiin 等不进去, 登陆的时候, 在请求登陆接口的时候, 首先重置了验证码,

**Comment by Jiiiiiin** [comment]
好的 我找时间看看那个分支，目前助攻springcloud分支 哈哈哈(ಡωಡ)hiahiahia

**Comment by SLin0218** [comment]
@Jiiiiiin  谢谢 , 哈哈我先从简单的入手。

**Comment by H786019030** [comment]
@Jiiiiiin @SLin0218  在登陆的时候 vue 捕获异常在刷新验证码就好了
src/pages/login/custom-page.vue 在这个文件里面
![Uploading image.png…]()
这样改应该没错吧，没具体学过

**Comment by Jiiiiiin** [comment]
@H786019030 我明天同步一下代码测试一下 @SLin0218

**Comment by Jiiiiiin** [comment]
@H786019030 @SLin0218 我啥都没改就登进去了~~ 不过我还是把新的一些代码尽量同步过来，springboot也将会升级到2.0

**Comment by Jiiiiiin** [comment]
@SLin0218 你们可以参考视频教程 https://coding.imooc.com/class/chapter/134.html#Anchor 关于验证码的章节~~

**Comment by Jiiiiiin** [comment]
@SLin0218 @H786019030 我测试出来了，通过测试应该不是本身代码的问题，应该是webpack-dev-server底层代理机制导致的session id每次过去都不一致导致的，目前我改为和springcloud分支相同的处理方式使用redis来存储这个东西，就解决了，详细可以看提交的代码，然后针对后端验证码生成的逻辑可以看视频，也可以参考：https://mrbird.cc/Spring-Security-ValidateCode.html
