### ISSUE TITLE
怎么这么多Bug？

### ISSUE THREAD

**Issue by yqtech** [Jiiiiiin/jiiiiiin-security#16]

**Comment by Jiiiiiin** [comment]
@yqtech 请列出你测出的bug 目前除了`feature/springcloud`分支，其他分支的bug暂时没时间修，主要精力还是放在这个分支，谢谢，给你带来麻烦了

**Comment by jiangbaojia** [comment]
> @yqtech 请列出你测出的bug 目前除了`feature/springcloud`分支，其他分支的bug暂时没时间修，主要精力还是放在这个分支，谢谢，给你带来麻烦了

cn.jiiiiiin.data.config
这里的@AutoConfigureAfter(RedisAutoConfiguration.class)好像不起效，一旦redis设置了密码，仍然会覆盖掉，然后报异常

**Comment by Jiiiiiin** [comment]
@jiangbaojia 我明天试试

**Comment by Jiiiiiin** [comment]
@jiangbaojia 已经修复 https://github.com/Jiiiiiin/jiiiiiin-security/commit/271a5496dadc6918d86fceef025e9ea608851a0e 不过建议生产环境做物理网络隔离，配不配密码就无所谓了

**Comment by jiangbaojia** [comment]
> @jiangbaojia 已经修复 [271a549](https://github.com/Jiiiiiin/jiiiiiin-security/commit/271a5496dadc6918d86fceef025e9ea608851a0e) 不过建议生产环境做物理网络隔离，配不配密码就无所谓了

OK

**Comment by jiangbaojia** [comment]
> @jiangbaojia 已经修复 [271a549](https://github.com/Jiiiiiin/jiiiiiin-security/commit/271a5496dadc6918d86fceef025e9ea608851a0e) 不过建议生产环境做物理网络隔离，配不配密码就无所谓了
我刚拉了代码，
其实可能还需要在48行和49行代码中插入
template.afterPropertiesSet();
才能解决这个问题

**Comment by Jiiiiiin** [comment]
@jiangbaojia 单节点我实测过了 不过现在没花太多时间去深究因为之后会上集群 到时候在整理这一块的代码，不过欢迎pr

**Comment by jiangbaojia** [comment]
> @jiangbaojia 单节点我实测过了 不过现在没花太多时间去深究因为之后会上集群 到时候在整理这一块的代码，不过欢迎pr

明白，努力follow中，感谢

**Comment by Jiiiiiin** [comment]
@jiangbaojia 谢谢理解

**Comment by Jiiiiiin** [comment]
如果测出新的问题欢迎 issue
