### ISSUE TITLE
parrent pom

### ISSUE THREAD

**Issue by fu1744** [Jiiiiiin/jiiiiiin-security#2]
在父pom文件中存在
<module>jiiiiiin-security-demo</module>
这个module不存在，作者删掉更新下吧

**Comment by Jiiiiiin** [comment]
好的 谢谢，下午我解决一下

**Comment by Jiiiiiin** [comment]
> 在父pom文件中存在
> jiiiiiin-security-demo
> 这个module不存在，作者删掉更新下吧

Commit 8b5adde42b2972ab814ee41f0951c9d677cbb8f3 closes #2

**Comment by fu1744** [comment]
想问问sql脚本怎么导入的，我用navicat倒入报错呀




| |
付建鑫
邮箱：15046688640@163.com
|

签名由 网易邮箱大师 定制

On 12/21/2018 14:59, 赵津 wrote:

Closed #2.

**Comment by Jiiiiiin** [comment]
@fu1744 因为spring social 默认那张表最新版mysql不支持，只能用于5.x版本

**Comment by Jiiiiiin** [comment]
另外就是检查`CREATE USER`是否重复了。
