### ISSUE TITLE
3个项目启动的问题

### ISSUE THREAD

**Issue by JingZhangs** [Jiiiiiin/jiiiiiin-security#6]
代码没有任何改动，就是直接clone下的你的仓库配置然后运行。

## Q1:
1. 前端运行后会报下面的`[WDS] Disconnected!`不知道有没有影响
2. 输入验证码点登陆后会有跨域问题
<img width="1242" alt="2019-01-04 16 47 47" src="https://user-images.githubusercontent.com/46194758/50679968-aee97e80-1040-11e9-87e5-c94d2838c41d.png">

## Q2:
从`sessionStrategy`里取不到`code`，出现验证码不存在的异常。
sessionStrategy.setAttribute(request, getSessionKey(request, validateCodeType), code);时
`request=`
ServletWebRequest: uri=/mng/code/image;client=127.0.0.1;session=50706529-44d6-4b2a-aadd-e7c5a25fee68

return (ValidateCode) sessionStrategy.getAttribute(request, getSessionKey(request, validateCodeType));
`request=`
ServletWebRequest: uri=/mng/authentication/form;client=127.0.0.1

## Q3:
前端有热更新吗？

**Comment by Jiiiiiin** [comment]
针对问题2，请看 #5 
针对问题1，请看[快速开始](https://github.com/Jiiiiiin/jiiiiiin-security#快速开始)，前端使用vue-cli初始化的解构，那么前后端分离势必需要解决跨域，`配置服务端uri：`就是在使用webpack-server插件解决开发期间的跨域
针对问题3，整个前端项目结构完全遵循vue官方构建和开发方式，热更新是肯定有的，建议你先看看webpack-server相关文档。
